### ISSUE TITLE
make html read only

### ISSUE THREAD

**Issue by pyluyten** [jerry40/the-old-mode#3]
trivial patch so shr rendered article is not amendable.

[0001-make-html-read-only.patch.txt](https://github.com/jerry40/the-old-mode/files/1439667/0001-make-html-read-only.patch.txt)

**Comment by pyluyten** [comment]
also for me, the (other-window 1) does come back to list, while i would expect cursor to remain in rendered article.

[0002-do-not-switch-back-to-list-when-displaying-an-articl.txt](https://github.com/jerry40/the-old-mode/files/1439670/0002-do-not-switch-back-to-list-when-displaying-an-articl.txt)

**Comment by pyluyten** [comment]
note i am attaching patches but i can also use another way if you prefer

**Comment by jerry40** [comment]
You can commit code in repository, it is ok for me. I've added you to "contributors" list, you have rights to commit here I believe.
Inetersting decision with other-window, I'm ok with patches! Commit changes please, thanks!

**Comment by pyluyten** [comment]
ok thanks, i pushed the r-o mode and removal of "other-window". Next, i'm proposing to use a local map for shr rendered articles so you can navigate (well it's just few keys, like q to quit)

- to code this quickly, i borrowed from elfeed (elfeed-show.el). I saw elfeed doing this and actually this was the idea i had in mind (but i did not know "use-local-map" before looking at elfeed). Elfeed is free software, plus, the borrowing is really really trivial so there is no real licence question.
- elfeed seems to go a bit further, because there is a dedicated mode. I did not implement a mode yet.
  first because i would like your opinion ! then because i'm not sure we really need a mode. Also i want to understand showing articles with <RET> instead of "e" (shr). Is <RET> just the summary & the prefered way?

One thing elfeed seems to offer is to navigate to next/previous article from the articles view. Well like the old reader web !

what do you think?
[0003-add-a-keymap-for-shr-buffer.txt](https://github.com/jerry40/the-old-mode/files/1442395/0003-add-a-keymap-for-shr-buffer.txt)

**Comment by jerry40** [comment]
Interesting, let me test it a bit later! To read an article, I added two possibilities:
1) e - to quickly open it in Emacs (in case a user is in text mode or the article is lightweight
2) w - to open it in default browser. Personally I prefer e-way, but browsers are way better at showing pages of course!
Which way do you prefer?

**Comment by pyluyten** [comment]
obviously i prefer the Emacs way with shr =)

i don't have xwidget on Arch Linux distributed Emacs version, so i cannot test, but i guess in the future this will be a serious alternative.

**Comment by jerry40** [comment]
Hi!

I committed some old changes (forgot to commit them long ago), also I committed your patch, sorry I did it by myself, it is because of merging issues on my side. Added 'h' message and "mark all read"  (C+r) on the subscription. Also I've changed keybinding from 'm' to "TAB" in order to change "mode" folders/subscriptions/articles.

**Comment by pyluyten** [comment]
i propose to close this issue  ; it seems other issues are properly tracking stuff
