### ISSUE TITLE
Please choose a licence

### ISSUE THREAD

**Issue by pyluyten** [jerry40/the-old-mode#4]

**Comment by jerry40** [comment]
I believe I did, not sure though. Can you check if I added it correctly?

**Comment by pyluyten** [comment]
great! to me it is fine. Some authors add a brief version of the licence on each file - i think this might be required to enter melpa -. Emacs conventions go a bit further :

https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html#Library-Headers
