### ISSUE TITLE
few bindings are not consistent with dired, or too difficult

### ISSUE THREAD

**Issue by pyluyten** [jerry40/the-old-mode#6]
I'm a fan of bindings, and very pesky about it!!!

I looked @ dired and ibuffer, and i found few bindings could be more consistent.
Also, some bindings are currently difficult (there are "w" and "W", M-a, C-r..., while we talk about 19 bindings for all)

Remove subscription, current = DEL, i propose to add d as in dired
Get row id, i propose to make it o or another letter (easier)
Switch mode, current TAB, i propose to add m (easier)
Show article, currently RET. I propose v like in dired. And to remove RET to use it for below : 
Shr article, currently e. I propose RET for this, and also j (as in dired jump-to).
kill new address, currently W, i propose c (easier)
Refresh, currently R, i propose g as in dired and easier
Redraw (clear filters), currently M-a, i propose l   (the letter l, not the pipe |)
Mark all read, currently C-r, i propose * as in dired and easier
toggle read unread, currently SPC, i propose to add t as in dired

no change for : n next line, p previous line, h help, q quit = as in dired or others
no change for : i get row id, w browse url, u mark unread, s star = easy

**Comment by jerry40** [comment]
I have no objections. Let's migrate to these. Also, I want to make keybindings tuneable from .emacs. I'll change keybindings today.

**Comment by jerry40** [comment]
Created `keybindings` branch with these keybindings, could you test it please?

**Comment by pyluyten** [comment]
in the help message, there is stil "<e> open in emacs". You can simply remove this because you already added the help "<RET> browse article in emacs (SHR)".

Otherwise i do not find any issue

**Comment by jerry40** [comment]
Fixed, thanks!

**Comment by pyluyten** [comment]
i think issue might be closed now? if i was wrong sorry, please re-open
